spring.application.name=javaSpringBE

#  with wildcard * all endpoints would be enabled
# certain endpoints with a comma de-limited string list

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name = javaSpringBE
info.app.description = Basic Java Spring Backend App with REST api made with Udemy course
info.app.version = 1.0.0

spring.security.user.name=exampleUser
spring.security.user.password=security123pass

# to exclude some endpoints:
# management.endpoints.web.exposure.exclude=health,info

coach.name=tdh
team.name=TDHteam

# changing Spring Boot embedded server port
server.port=7070

# setting the context path of the application
# all requests should be prefixed with /javaSpringBE
server.servlet.context-path=/javaSpringBE